# The global variable file mongodb installation

# The directory prefix where the database files would be stored
mongodb_datadir_prefix: /data/
#mongod_port: 27017
mongod_port_def: 27017
createStack: "{{ lookup('env','CREATE_STACK') }}"
stackname: "{{ lookup('env','STACK_NAME') }}"
template: "{{ lookup('env','CLOUDFORMATION_TEMPLATE') }}"
region: "{{ lookup('env','REGION') }}"
zone: "{{ lookup('env','AVAILABILITY_ZONE') }}"
replica_set: "{{ lookup('env','REPLICA_SET') }}"
iops: "{{ lookup('env','IOPS') }}"
nat_instance_type: "{{ lookup('env','NAT_INSTANCE_TYPE') }}"
node_instance_type: "{{ lookup('env','NODE_INSTANCE_TYPE') }}"
volume_type: "{{ lookup('env','VOLUME_TYPE') }}"
volume_size: "{{ lookup('env','VOLUME_SIZE') }}"
corpCidr: "{{ lookup('env','CORPORATE_CIDR') }}"
instances: "{{ lookup('env','INSTANCE_LIST') }}"
action: "{{ lookup('env','ACTION') }}"

# The interface where the mongodb process should listen on.
# Defaults to the first interface. Change this to:
# 
#  iface: eth1
#
# ...to override.
# 

iface: '{{ ansible_default_ipv4.interface }}'

# The password for admin user
mongo_admin_pass: 123456
