# The global variable file mongodb installation

# The directory prefix where the database files would be stored
mongodb_datadir_prefix: /data/
mongod_port: 27017
stackname: "{{ lookup('env','STACK_NAME') }}"


# The interface where the mongodb process should listen on.
# Defaults to the first interface. Change this to:
# 
#  iface: eth1
#
# ...to override.
# 

iface: '{{ ansible_default_ipv4.interface }}'

# The password for admin user
mongo_admin_pass: 123456