---
# This Playbook is to test the cloudformation ansible plugin

- hosts: localhost
  gather_facts: yes
  connection: local

  pre_tasks:
  - name: Get Info based On Tags
    ec2_remote_facts:
     region: eu-central-1
     filters:
       vpc-id: vpc-e427a58d
       "tag:Name": deploymentServer
    register: ec2
  - debug: var=ec2

  - name: Get Instance Names
    command: echo {{item.private_ip_address}}
    with_items: ec2.instances

  - name: Add all instance public IPs to host group
    add_host: hostname={{ item.private_ip_address }} groups=mongo_servers
    with_items: ec2.instances

  - name: list all hosts
    command: echo {{item}}
    with_items: groups['mongo_servers']

  roles:
    - { role: common, mongoDBInstances: "{{ec2}}" }
