---
# This Playbook is to test the cloudformation ansible plugin

- hosts: localhost
  gather_facts: no
  sudo: yes
  connection: local

  pre_tasks:
  - name: Get Info based On Tags
    ec2_remote_facts:
     region: eu-central-1
     filters:
       vpc-id: vpc-e427a58d
       "tag:Name": deploymentServer
    register: ec2

  
  - name: Add all instance public IPs to host group
    add_host: hostname={{ item.private_dns_name}} groups=mongo_servers
    with_items: ec2.instances


  roles:
    - { role: common, mongoDBInstances: "{{ec2.instances}}" }
