---
# This Playbook is to test the cloudformation ansible plugin

- hosts: localhost
  gather_facts: no
  sudo: yes
  connection: local

  pre_tasks:
  - name: Get Info based On Tags
    ec2_remote_facts:
     region: eu-central-1
     filters:
       vpc-id: vpc-05d55c6c
       "tag:Name": deploymentServer
    register: ec2

  
  - name: Add all instance public IPs to host group
    add_host: hostname={{ item.private_dns_name}} groups=mongo_servers
    with_items: ec2.instances

  - name: Install my ssh key
    sudo: yes
    sudo_user: ec2-user
    authorized_key: user=ec2-user
                    key="{{lookup('file', '/home/ansible/.ssh/mykey.pub')}}"
    delegate_to: mongo_servers

  roles:
    - { role: common, mongoDBInstances: "{{ec2.instances}}", delegate_to: mongo_servers}
