---
# This Playbook is to test the cloudformation ansible plugin

- hosts: localhost
  gather_facts: no
  sudo: yes
  connection: local

  tasks:

  - name: Stop Instances
    ec2:
     instance_ids: "{{item|regex_replace('^.*?-[^abc]')}}"
     state: stopped
     region: "{{region}}"
     wait: yes
    with_items: "{{instances.split(',')}}"
    when: action == "Stop Instances"

  - name: Start Instances
    ec2:
     instance_ids: "{{item|regex_replace('^.*?-[^abc]')}}"
     state: running
     region: "{{region}}"
     wait: yes
    with_items: "{{instances.split(',')}}"
    when: action == "Start Instances"

  - name: Terminate Stack
    cloudformation:
     template_url: "https:ffff" 
     stack_name: "{{stackname}}"
     state: absent
     region:  "{{region}}"
    when: action=="Destroy Stack"
