---
# This Playbook is to test the cloudformation ansible plugin

- hosts: localhost
  gather_facts: no
  sudo: yes
  connection: local

  tasks:
  - name: update CF Template
    command: aws s3 cp /home/ansible/staging/files/cloudtemplate_vpc.txt s3://cftemplates-gf/cloudtemplate_vpc.txt
  - name: launch ansible MongoDB cloudformation
    cloudformation:
     stack_name: "{{stackname}}"
     state: "present"
     region: "{{region}}"
     disable_rollback: false
     template_url: "https://s3.eu-central-1.amazonaws.com/cftemplates-gf/cloudtemplate_vpc.txt"
     template_parameters:
      AvailabilityZone0: "{{zone}}"
      ClusterReplicaSetCount: "{{replica_set}}"
      RemoteAccessCIDR: "{{corpCidr}}"
      VolumeSize: "{{volume_size}}"
      VolumeType: "{{volume_type}}"
      Iops: "{{iops}}"
      NATInstanceType: "{{nat_instance_type}}"
      NodeInstanceType: "{{node_instance_type}}"
     tags:
      Stack: "ansible-{{stackname}}"
    when: createStack == "Yes"


  - name: Get VPC
    ec2_vpc_subnet_facts:
     region: "{{region}}"
     filters:
        "tag:aws:cloudformation:stack-name": "{{stackname}}"
    register: curvpc

  - name: Get Info based On Tags
    ec2_remote_facts:
     region: "{{region}}"
     filters:
       vpc-id: "{{curvpc.subnets[0].vpc_id}}"
       "tag:Type": MongoDBReplica
    register: ec2


  - name: Add all instance public IPs to host group
    add_host: hostname={{item.private_dns_name|regex_replace('\.\S+')}}
              ansible_ssh_private_key_file="/home/ansible/.ssh/mykey.pem"			  
              groups=mongo_servers
              mongod_port={{mongod_port_def+item.tags.NodeReplicaSetIndex|int}}
    with_items: ec2.instances
    when: "{{replica_set}} == '1'"
  
  - name: Add all instance public IPs to host group when replica is greater
    add_host: hostname={{item.private_dns_name|regex_replace('\.\S+')}}
              groups=mongo_servers
              ansible_ssh_private_key_file="/home/ansible/.ssh/mykey.pem"
              mongod_port={{mongod_port_def+item.tags.NodeReplicaSetIndex|int}}
              mongo_dns_name={{item.private_dns_name}}
    with_items: ec2.instances
    when: "{{replica_set}} == '3'" 

  - name: Create Primary mongoDB Host group
    add_host: hostname={{item.private_dns_name|regex_replace('\.\S+')}}
              groups=mongo_primary
              ansible_ssh_private_key_file="/home/ansible/.ssh/mykey.pem"
              mongod_port=27017
    with_items: ec2.instances
    when: "{{replica_set}} == '3' and {{item.tags.NodeReplicaSetIndex|int}} == '0'"


  - name: Add all instance public IPs to host group for Replica Set
    add_host: hostname={{item.private_dns_name|regex_replace('\.\S+')}}
              groups=replication_servers
              ansible_ssh_private_key_file="/home/ansible/.ssh/mykey.pem"
              mongod_port={{mongod_port_def+item.tags.NodeReplicaSetIndex|int}}
    with_items: ec2.instances
    when: "{{replica_set}} == '3'"

  - name: Change private key permission
    file: path=/home/ansible/.ssh/id_rsa.pub mode=0400

  - name: Wait for instance to start up and be running
    wait_for: host={{item.private_ip_address}} port=22 delay=1 timeout=320 state=started
    with_items: ec2.instances

  - name: Create the hosts file for the local machine
    sudo: yes
    template: src=/home/ansible/staging/files/inventory.j2 dest=/etc/hosts

- hosts: mongo_servers
  gather_facts: yes
  remote_user: ec2-user
  serial: 1

  tasks:
  - name: Pause
    pause: seconds=5
  
- hosts: mongo_servers
  gather_facts: yes
  remote_user: ec2-user
  serial: 1

  pre_tasks:
  - debug: var=hostvars[inventory_hostname]

  - name: Install ansible key
    authorized_key: user=ec2-user
                    key="{{lookup('file', '/home/ansible/.ssh/id_rsa.pub')}}"

  roles:
  - { role: common }

  post_tasks:
  - name: Pause
    pause: seconds=5


- hosts: mongo_servers
  gather_facts: yes
  remote_user: ec2-user
  serial: 1


  roles:
  - { role: mongod, when: "{{replica_set}} == 3"}
  
  post_tasks:

  - name: Remove bind ip
    become: yes
    become_method: sudo
    replace: dest=/etc/mongod.conf regexp="^bind_ip=127.0.0.1" replace="#bind_ip=127.0.0.1"
    when: "{{replica_set}} == '1'"

  - name: Start Mongodb
    become: yes
    become_method: sudo
    service: name=mongod state=restarted
    when: "{{replica_set}} == '1'"

  - name: Pause
    pause: seconds=5

- hosts: mongo_primary
  gather_facts: yes
  remote_user: ec2-user

  tasks:
#  - debug: var=hostvars[inventory_hostname]
#  - name: Pause
#    pause: seconds=5

  - name: Initialize the replication set
    sudo: yes
    shell: /usr/bin/mongo --port "{{hostvars[inventory_hostname].mongod_port }}" /tmp/repset_init.js
    when: "{{hostvars[inventory_hostname].mongod_port}} == '27017' and {{replica_set}} == '3'"

  - name: Get MongoDB example
    run_once: yes
    become: yes
    become_method: sudo
    become_user: mongod
    get_url: url=https://raw.githubusercontent.com/mongodb/docs-assets/primer-dataset/dataset.json
         dest="/tmp/primer-dataset.json"


  - name: Import dataset into mongodb
    run_once: yes
    become: yes
    become_method: sudo
    become_user: mongod
    shell: mongoimport --db test --collection restaurants --drop --file /tmp/primer-dataset.json

  - name: Create root user
    run_once: yes
    become: yes
    become_method: sudo
    become_user: mongod
    mongodb_user: database=admin
                  name=root
                  password=12345 
                  roles='root' 
                  state=present
                  login_port="{{hostvars[inventory_hostname].mongod_port }}"

- hosts: localhost
  gather_facts: no

  tasks:
  roles:
  - { role: aws }
