---
# This Playbook is to test the cloudformation ansible plugin

- hosts: localhost
  gather_facts: no
  sudo: yes
  connection: local

  tasks: 
  - name: Get Info based On Tags
    ec2_remote_facts:
     region: "{{region}}"
     filters:       
       "tag:Type": mongoSVT
    register: ec2


  - name: Add all instance public IPs to host group
    add_host: hostname={{item.private_dns_name|regex_replace('\.\S+')}}
              ansible_ssh_private_key_file="/home/ansible/.ssh/mykey.pem"			  
              groups=mongo_svt
              mongod_port={{mongod_port_def+item.tags.NodeReplicaSetIndex|int}}
    with_items: ec2.instances
    
  - name: Change private key permission
    file: path=/home/ansible/.ssh/id_rsa.pub mode=0400

  - name: Wait for instance to start up and be running
    wait_for: host={{item.private_ip_address}} port=22 delay=1 timeout=320 state=started
    with_items: ec2.instances

  - name: Create the hosts file for the local machine
    sudo: yes
    template: src=/home/ansible/staging/files/inventory.j2 dest=/etc/hosts

- hosts: mongo_svt
  gather_facts: yes
  remote_user: ec2-user  

  tasks:
  - name: Pause
    pause: seconds=5
  
- hosts: mongo_svt
  gather_facts: yes
  remote_user: ec2-user
  

  pre_tasks:
  - debug: var=hostvars[inventory_hostname]

  - name: Install ansible key
    authorized_key: user=ec2-user
                    key="{{lookup('file', '/home/ansible/.ssh/id_rsa.pub')}}"

  roles:
  - { role: ycsb }

  post_tasks:
  - name: Pause
    pause: seconds=5
