---
# Handler for mongod

- name: restart iptables
  become: yes
  become_method: sudo
  service: name=iptables state=restarted
  
- name: restart mongod
  become: yes
  become_method: sudo
  service: name=mongod state=restarted