- name: Create the hosts file for all machines
  become: yes
  become_method: sudo
  template: src=hosts.j2 dest=/etc/hosts
  
- name: Create the data directory for the namenode metadata
  become: yes
  become_method: sudo
  file: path="{{item.dirname}}" owner=mongod group=mongod state=directory
  with_items:
      - { dirname: '/data' }
      - { dirname: '/data/mongo'}

- name: Create the data directory FS 
  become: yes
  become_method: sudo
  filesystem: fstype=ext4 dev=/dev/xvdf

- name: Append Entry in fstab
  become: yes
  become_method: sudo
  lineinfile: dest=/etc/fstab line="/dev/xvdf /data ext4 defaults,auto,noatime,noexec 0 0" create=yes state=present

- name: Mount the data FS
  become: yes
  become_method: sudo
  mount: name=/data src=/dev/xvdf state=mounted fstype=ext4

 
- name: Create the log directory for the namenode metadata
  become: yes
  become_method: sudo
  file: path="{{item.dirname}}" owner=mongod group=mongod state=directory
  with_items:
      - { dirname: '/log' }
      - { dirname: '/log/mongodb'}
  

- name: Create the log directory FS 
  become: yes
  become_method: sudo
  filesystem: fstype=ext4 dev=/dev/xvdg

- name: Append Entry in fstab for log dir
  become: yes
  become_method: sudo
  lineinfile: dest=/etc/fstab line="/dev/xvdg /log ext4 defaults,auto,noatime,noexec 0 0" create=yes state=present

- name: Mount the log FS
  become: yes
  become_method: sudo
  mount: name=/log src=/dev/xvdg state=mounted fstype=ext4

- name: Create the journal directory for the namenode metadata
  become: yes
  become_method: sudo
  file: path=/journal owner=mongod group=mongod state=directory
  
- name: Create the journal directory FS 
  become: yes
  become_method: sudo
  filesystem: fstype=ext4 dev=/dev/xvdh
  
- name: Append Entry in fstab for journal
  become: yes
  become_method: sudo
  lineinfile: dest=/etc/fstab line="/dev/xvdh /journal ext4 defaults,auto,noatime,noexec 0 0" create=yes state=present

- name: Mount the journal FS
  become: yes
  become_method: sudo
  mount: name=/journal src=/dev/xvdh state=mounted fstype=ext4

- name: Create a symlink from /data/jorunal to journal FS
  become: yes
  become_method: sudo
  file: src=/journal dest=/data/journal owner=mongod group=mongod state=link
  
- name: Change File Limits
  become: yes
  become_method: sudo
  lineinfile: 
    dest: /etc/security/limits.conf
    line: "{{item.line}}"
    create: yes 
    state: present
  with_items: 
      - { line: '* soft nofile 64000' }
      - { line: '* hard nofile 64000' }
      - { line: '* soft nproc 32000' }
      - { line: '* hard nproc 32000' }

- name: Change nProc File Limits
  become: yes
  become_method: sudo
  lineinfile:
    dest: /etc/security/limits.d/90-nproc.conf
    line: "{{item.line}}"
    create: yes 
    state: present    
  with_items: 
      - { line: '* soft nproc 32000' }
      - { line: '* hard nproc 32000' }

- name: Set readahead blocdev 
  become: yes
  become_method: sudo
  shell: "blockdev --setra 32 {{item.device}}"
  with_items: 
      - { device: '/dev/xvdf' }
      - { device: '/dev/xvdg' }
      - { device: '/dev/xvdh' }

- name: Add readahead blocdev to startup
  become: yes
  become_method: sudo
  lineinfile:
      dest: /etc/rc.local
      line: "/sbin/blockdev --setra 32 {{item.device}}"
      create: yes 
      state: present    
  with_items: 
      - { device: '/dev/xvdf' }
      - { device: '/dev/xvdg' }
      - { device: '/dev/xvdh' }

- name: Add readahead blocdev limits to ebs rules
  become: yes
  become_method: sudo
  lineinfile:
    dest: /etc/udev/rules.d/85-ebs.rules
    line: 'ACTION=="add", KERNEL=="{{item.device}}", ATTR{bdi/read_ahead_kb}="16"'
    create: yes 
    state: present    
  with_items: 
      - { device: '/dev/xvdf' }
      - { device: '/dev/xvdg' }
      - { device: '/dev/xvdh' }

- name: Replace keep alive setting to 300 seconds
  become: yes
  become_method: sudo
  command: echo 300 | sudo tee /proc/sys/net/ipv4/tcp_keepalive_time

- name: Create the iptables file
  become: yes
  become_method: sudo
  template: src=iptables.j2 dest=/etc/sysconfig/iptables
  notify: restart iptables

- name: Install the latest pymongo package
  become: yes
  become_method: sudo
  pip: name=pymongo state=latest executable=/usr/bin/pip use_mirrors=no
  
- name: Create the mongodb configuration file
  become: yes
  become_method: sudo
  template: src=mongod.conf_primary.j2 dest=/etc/mongod.conf 
  notify: restart mongod