  - name: Get Info based On Tags
    connection: local
    ec2_remote_facts:
     region: eu-central-1
     filters:
       "tag:aws:cloudformation:stack-name": "{{stackname}}"
    register: AllInstances
  - debug: var=AllInstances

  - name: Create the email template
    connection: local
    template: src=email.j2 dest=/tmp/email.txt
	register: result
  - name: Send Email with Details
    local_action: mail
                  subject="Ansible MongoDB Creation Report"
                  from=ansible@poc.nl
                  to=gordon.fava@t-mobile.nl
                  body="{{ lookup('file', '/tmp/email.txt') }}"
	changed_when: result|success
  - name: Remove email file
    become: yes
    become_method: sudo
    file: path=/tmp/email.txt state=absent