  - name: Get Info based On Tags
    connection: local
    ec2_remote_facts:
     region: eu-central-1
     filters:
       "tag:aws:cloudformation:stack-name": "{{stackname}}"
    register: AllInstances
  - debug: var=AllInstances

  - name: Create the email template  
    connection: local
    template: src=email.j2 dest=/tmp/email.txt
